### ISSUE TITLE
Missing the "Pokemon" class.

### ISSUE THREAD

**Issue by atheriel** [OSPokemon/api-java#9]
Currently the `Pokemon` class is stubbed. For `0.1`, this should no longer be the case. The necessary fields seem to be:

_Personality:_
- Name
- Species
- (Hidden) Ability
- Nature
- Gender
- Shiny
- OT Name/No/Gender
- Ball Used
- Place Caught 

_Stats:_ 
- Level
- IVs
- EVs
- Current HP
- Egg Steps
- Happiness
- Experience Total

_Temporary Assets:_
- Held Item
- Pokerus
- StatusAilment

**Comment by atheriel** [comment]
@zachtaylor Let me know if I've missed anything.

**Comment by zachtaylor** [comment]
I don't know about anything missing yet, but a couple questions.

Are the groupings significant? Will they be classes inside a Pokemon, or is that a way to sort?

Does a Pokemon know it's egg steps, or is this just on the species?

Will the field be called "experience total"? Some implementations may use that, or may use experience above level. The word "experience" may be good.

Do you mean Held Item as an actual item reference or as a string?

StatusAilment should be a list, because a pokemon could have multiple, such as confused / poisoned.

**Comment by atheriel** [comment]
The groupings were completely arbitrary. I didn't specify types for the fields because I'm not really sure about some of them yet.

I think we just need to decide how many of the derived stats (level, experience to level, hp/atk/def/sp/spd) that can be calculated from the ivs/evs/experience total should be first-class fields of their own.

The egg steps in the Pokemon class refers to the number of steps you've walked with them as an egg (as opposed to the species value stepsToHatch). In theory, we could just have an Egg class to simplify things.

**Comment by zachtaylor** [comment]
hp/atk/... defintely. I think that experience, level, and current health should be Stats, since they can be configured to be there or not, and it gives implementations a hook if they want to put data on stats (such as rested experience, current health shielding, etc). Possibly egg steps is a stat that can get removed when the pokemon hatches?
